In [20]:
import pandas as pd
import os

In [6]:
df = pd.read_csv(
    "../HIST_PAINEL_COVIDBR_21out2023/HIST_PAINEL_COVIDBR_2020_Parte1_24out2023.csv",
    sep=";"
    )
df

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-25,9.0,210147125.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-26,9.0,210147125.0,1.0,1.0,0.0,0.0,1.0,0.0,NaN
2,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-27,9.0,210147125.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN
3,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-28,9.0,210147125.0,1.0,0.0,0.0,0.0,0.0,1.0,NaN
4,Brasil,NaN,NaN,76,NaN,NaN,NaN,2020-02-29,9.0,210147125.0,2.0,1.0,0.0,0.0,1.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
713457,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-07-27,31.0,3015268.0,98480.0,2148.0,1339.0,31.0,NaN,NaN,1.0
713458,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-07-28,31.0,3015268.0,100726.0,2246.0,1391.0,52.0,NaN,NaN,1.0
713459,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-07-29,31.0,3015268.0,102342.0,1616.0,1419.0,28.0,NaN,NaN,1.0
713460,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-07-30,31.0,3015268.0,104442.0,2100.0,1444.0,25.0,NaN,NaN,1.0
713461,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-07-31,31.0,3015268.0,106292.0,1850.0,1469.0,25.0,NaN,NaN,1.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713462 entries, 0 to 713461
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   regiao                  713462 non-null  object
 1   estado                  713304 non-null  object
 2   municipio               706371 non-null  object
 3   coduf                   713462 non-null  int64
 4   codmun                  709038 non-null  float64
 5   codRegiaoSaude          706371 non-null  float64
 6   nomeRegiaoSaude         706371 non-null  object
 7   data                    713461 non-null  object
 8   semanaEpi               713461 non-null  float64
 9   populacaoTCU2019        710795 non-null  float64
 10  casosAcumulado          713461 non-null  float64
 11  casosNovos              713461 non-null  float64
 12  obitosAcumulado         713461 non-null  float64
 13  obitosNovos             713461 non-null  float64
 14  Recuperadosnovos        158 non-null     float64
 15  emAcompanhamentoNovos   158 non-null     float64
 16  interior/metropolitana  706370 non-null  float64
dtypes: float64(11), int64(1), object(5)
memory usage: 92.5+ MB

In [16]:
df_sp = df[df["estado"] == "SP"]

In [18]:
df_sp[df_sp["municipio"].isna()].drop_duplicates(subset="data")

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
3160,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-02-25,9.0,45919049.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3161,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-02-26,9.0,45919049.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN
3162,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-02-27,9.0,45919049.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN
3163,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-02-28,9.0,45919049.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN
3164,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-02-29,9.0,45919049.0,2.0,1.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3313,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-07-27,31.0,45919049.0,487654.0,3672.0,21676.0,70.0,NaN,NaN,NaN
3314,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-07-28,31.0,45919049.0,487654.0,0.0,21676.0,0.0,NaN,NaN,NaN
3315,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-07-29,31.0,45919049.0,514197.0,26543.0,22389.0,713.0,NaN,NaN,NaN
3316,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-07-30,31.0,45919049.0,529006.0,14809.0,22710.0,321.0,NaN,NaN,NaN
3317,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-07-31,31.0,45919049.0,542304.0,13298.0,22997.0,287.0,NaN,NaN,NaN

### Concatenar todos os files

In [22]:
files = os.listdir("../HIST_PAINEL_COVIDBR_21out2023/")
df_all = pd.DataFrame()
for file in files:

    tmp = pd.read_csv(f"../HIST_PAINEL_COVIDBR_21out2023/{file}", sep=";")
    df_all = pd.concat([df_all, tmp], axis="rows")

In [24]:
df_all_sp = df_all[df_all["estado"] == "SP"]
df_all_sp

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
3060,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-01,31.0,45919049.0,552318.0,10014.0,23236.0,239.0,NaN,NaN,NaN
3061,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-02,32.0,45919049.0,558685.0,6367.0,23317.0,81.0,NaN,NaN,NaN
3062,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-03,32.0,45919049.0,560218.0,1533.0,23365.0,48.0,NaN,NaN,NaN
3063,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-04,32.0,45919049.0,575589.0,15371.0,23702.0,337.0,NaN,NaN,NaN
3064,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-05,32.0,45919049.0,585265.0,9676.0,24109.0,407.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716031,Sudeste,SP,Estiva Gerbi,35,355730.0,35141.0,BAIXA MOGIANA,2023-06-26,26.0,11304.0,1271.0,0.0,37.0,0.0,NaN,NaN,0.0
716032,Sudeste,SP,Estiva Gerbi,35,355730.0,35141.0,BAIXA MOGIANA,2023-06-27,26.0,11304.0,1271.0,0.0,37.0,0.0,NaN,NaN,0.0
716033,Sudeste,SP,Estiva Gerbi,35,355730.0,35141.0,BAIXA MOGIANA,2023-06-28,26.0,11304.0,1271.0,0.0,37.0,0.0,NaN,NaN,0.0
716034,Sudeste,SP,Estiva Gerbi,35,355730.0,35141.0,BAIXA MOGIANA,2023-06-29,26.0,11304.0,1271.0,0.0,37.0,0.0,NaN,NaN,0.0
716035,Sudeste,SP,Estiva Gerbi,35,355730.0,35141.0,BAIXA MOGIANA,2023-06-30,26.0,11304.0,1271.0,0.0,37.0,0.0,NaN,NaN,0.0

In [26]:
df_all_sp[df_all_sp["municipio"].isna()].drop_duplicates(subset="data")

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
3060,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-01,31.0,45919049.0,552318.0,10014.0,23236.0,239.0,NaN,NaN,NaN
3061,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-02,32.0,45919049.0,558685.0,6367.0,23317.0,81.0,NaN,NaN,NaN
3062,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-03,32.0,45919049.0,560218.0,1533.0,23365.0,48.0,NaN,NaN,NaN
3063,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-04,32.0,45919049.0,575589.0,15371.0,23702.0,337.0,NaN,NaN,NaN
3064,Sudeste,SP,NaN,35,NaN,NaN,NaN,2020-08-05,32.0,45919049.0,585265.0,9676.0,24109.0,407.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3796,Sudeste,SP,NaN,35,NaN,NaN,NaN,2023-06-26,26.0,45919049.0,6629875.0,0.0,180612.0,0.0,NaN,NaN,NaN
3797,Sudeste,SP,NaN,35,NaN,NaN,NaN,2023-06-27,26.0,45919049.0,6629875.0,0.0,180612.0,0.0,NaN,NaN,NaN
3798,Sudeste,SP,NaN,35,NaN,NaN,NaN,2023-06-28,26.0,45919049.0,6629875.0,0.0,180612.0,0.0,NaN,NaN,NaN
3799,Sudeste,SP,NaN,35,NaN,NaN,NaN,2023-06-29,26.0,45919049.0,6629875.0,0.0,180612.0,0.0,NaN,NaN,NaN
3800,Sudeste,SP,NaN,35,NaN,NaN,NaN,2023-06-30,26.0,45919049.0,6629875.0,0.0,180612.0,0.0,NaN,NaN,NaN